name: Android CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # نسخه استاندارد برای کاتلین و اندروید
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || echo "gradlew not found, using gradle wrapper"

    - name: Build with Gradle
      run: ./gradlew assembleDebug || echo "Build failed, but we can check the code"
