name: Diagnostic Workflow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  check_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # رفع اخطار نسخه ۲۰

    - name: List all files
      run: ls -R # این دستور فقط لیست فایل‌های شما را چاپ می‌کند و هیچ خطایی نمی‌دهد
